ordersapp/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path
from django.conf import settings
from ordersapp.views import OrderList, OrderCreate, OrderUpdate, OrderDelete, OrderDetail, order_forming_complete, get_product_price

app_name = 'orders'

urlpatterns = [
    path('', OrderList.as_view(), name='list'),
    path('create/', OrderCreate.as_view(), name='create'),
    path('update/<int:pk>/', OrderUpdate.as_view(), name='update'),
    path('read/<int:pk>/', OrderDetail.as_view(), name='read'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='delete'),
    path('forming_complete/<int:pk>/', order_forming_complete, name='forming_complete'),
    path('product/<int:pk>/price/', get_product_price, name='product_price'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ordersapp/models.py
from django.conf import settings
from django.db import models

# Create your models here.
from product.models import Product

class Order(models.Model):
    FORMING = 'FM'
    SEND_TO_PROCEED = 'STP'
    PAID = 'PD'
    PROCRRDED = 'PDR'
    READY = 'RDY'
    CANCEL = ' CNC'

    ORDER_STATUS_CHOIXES = (
        (FORMING, 'формируется'),
        (SEND_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачено'),
        (PROCRRDED, 'обрабатывается'),
        (READY, 'готов к выдачи'),
        (CANCEL, 'отмена заказа'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновление', auto_now=True)
    status = models.CharField(choices=ORDER_STATUS_CHOIXES, verbose_name='статус', max_length=4, default=FORMING)
    is_active = models.BooleanField(verbose_name='активный', default=True)

    def __str__(self):
        return f'Текущий заказ {self.pk}'

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.get_product_cost(), items)))

    def get_items(self):
        pass

    def delete(self, using=None, keep_parents=False):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.save()
        self.is_active = False
        self.save()

    def get_summary(self):
        items = self.orderitems.select_related()
        return {
            'get_total_cost': sum(list(map(lambda x: x.get_product_cost(), items))),
            'get_total_quantity': sum(list(map(lambda x: x.quantity, items))),
        }

class OrderItem(models.Model):
    order = models.ForeignKey(Order, verbose_name='заказ', related_name='orderitems', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='продукты', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk).quantity

ordersapp/templates/ordersapp/includes/inc_order_actions.html
{% if object.status == 'FM' %}
    <div class="container">
        <div class="d-flex justify-content-around">
            <button class="btn btn-warning btn-round form-control w-25 my-2 last">
                <a href="{% url 'orders:forming_complete' object.pk %}">
                    совершить покупку
                </a>
            </button>
            <button class="btn btn-warning btn-round form-control w-25 my-2 last">
                <a href="{% url 'orders:delete' object.pk %}">удалить</a>
            </button>
        </div>
    </div>
{% endif %}
<div class="container">

    <button class="btn btn-info btn-round form-control my-2 last">
        <a href="{% url 'orders:list' %}">
            к списку заказов
        </a>
    </button>
    <button class="btn btn-light btn-round form-control  my-2 last">
        <a href="{% url 'index' %}">на главную</a>
    </button>
</div>

ordersapp/templates/ordersapp/includes/inc_order_summary.html
{% if object %}
   <div class="h2">Заказ №{{ object.pk }} от {{ object.created|date:"Y-m-d H:i:s" }}</div>
   <hr>
   <div class="h4">заказчик: {{ user.last_name }} {{ user.first_name }} </div>
   <div class="h4">обновлен: {{ object.updated|date:"Y-m-d H:i:s" }}</div>
   <div class="h4">cтатус: {{ object.get_status_display }}</div>
   <hr>
    {% with object_summary=object.get_summary %}
   <div class="h4">
       общее количество товаров: <span class="order_total_quantity">{{ object_summary.get_total_quantity }}</span>
   </div>
   <div class="h3">
       общая стоимость: <span class="order_total_cost">{{ object_summary.get_total_cost }}</span> руб
   </div>
    {% endwith %}
{% else %}
   <div class="h2">Новый заказ</div>
   <hr>
   <div class="h4">заказчик: {{ user.last_name }} {{ user.first_name }} </div>
   {% if basket.0 %}
       <div class="h4">
           общее количество товаров: <span class="order_total_quantity">{{ basket.0.get_total_quantity }}</span>
       </div>
       <div class="h3">
           общая стоимость: <span class="order_total_cost">{{ basket.0.get_total_cost }}</span> руб
       </div>
   {% endif %}
{% endif %}
<hr>