admins/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from product import views as prod, urls
from authnapp import urls as urls_aupp
from baskets import urls as urls_bask
from admins import urls as urls_adm
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    path('', prod.index, name='index'),
    path('admin/', admin.site.urls),
    path('products/', include(urls, namespace='products')),
    path('auth/', include(urls_aupp, namespace='auth')),
    path('baskets/', include(urls_bask, namespace='baskets')),
    path('admins/', include(urls_adm, namespace='admins')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admins/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from admins import views
from admins.views import UserListView, UserCreateView, UserUpdateView, UserDeleteView, CategoryListView, \
    CategoryCreateView, CategoryUpdateView, CategoryDeleteView, ProductListView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView

app_name = 'admins'

urlpatterns = [
    path('', views.index, name='index'),
    path('users/', UserListView.as_view(), name='admin_users'),
    path('user_update/<int:pk>', UserUpdateView.as_view(), name='admin_user_update'),
    path('user_create/', UserCreateView.as_view(), name='admin_user_create'),
    path('user_delete/<int:pk>', UserDeleteView.as_view(), name='admin_user_delete'),
    path('admin_category/', CategoryListView.as_view(), name='admin_category'),
    path('admin_category_create/', CategoryCreateView.as_view(), name='admin_category_create'),
    path('admin_categoryes_update/<int:pk>', CategoryUpdateView.as_view(), name='admin_categoryes_update'),
    path('admin_categoryes_delete/<int:pk>', CategoryDeleteView.as_view(), name='admin_categoryes_delete'),
    path('admin_product/', ProductListView.as_view(), name='admin_product'),
    path('admin_product_create/', ProductCreateView.as_view(), name='admin_product_create'),
    path('admin_product_update/<int:pk>', ProductUpdateView.as_view(), name='admin_product_update'),
    path('admin_product_delete/<int:pk>', ProductDeleteView.as_view(), name='admin_product_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admins/templates/admins/admin-users-create.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Создание пользователя</h1>
                <form action="{% url 'admins:admin_user_create'%}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{form.first_name.id_for_label}}">Имя</label>
                                {{form.first_name}}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{form.last_name.id_for_label}}">Фамилия</label>
                                {{form.last_name}}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{form.avatar}}
                                <label class="custom-file-label" for="{{form.avatar.id_for_label}}">Выберите изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-4">
                            <label class="small mb-1" for="{{form.username.id_for_label}}">Имя пользователя</label>
                            {{form.username}}
                        </div>
                        <div class="col-lg-4">
                            <label class="small mb-1" for="{{form.email.id_for_label}}">Адрес электронной
                                почты</label>
                            {{form.email}}
                        </div>
                        <div class="col-lg-4">
                            <label class="small mb-1" for="{{form.age.id_for_label}}">Возраст</label>
                            {{form.age}}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{form.password1.id_for_label}}">Пароль</label>
                            {{form.password1}}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{form.password2.id_for_label}}">Повторите пароль</label>
                            {{form.password2}}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-users-read.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">{{title}}</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        {{title}}
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">

                                <thead>

                                <tr>
                                    <th>Имя пользователя</th>
                                    <th>Имя</th>
                                    <th>Фамилия</th>
                                    <th>Адрес эл. почты</th>
                                    <th>Персонал сайта</th>
                                    <th>Активный</th>
                                </tr>
                                </thead>


                                <tbody>

                                    {% for el in shop_users %}
                                        <tr>
                                            <td><a href="{% url 'admins:admin_user_update' el.id %}" style="color: dodgerblue">{{el.username}}</a></td>
                                            <td>{{el.first_name}}</td>
                                            <td>{{el.last_name}}</td>
                                            <td>{{el.email}}</td>
                                            <td class="text-center">
                                                {% if el.is_staff %}
                                                    <i class="fas fa-check-circle"></i>
                                                {% else %}
                                                    <i class="fas fa-times-circle"></i>
                                                {% endif %}
                                            </td>
                                            <td class="text-center">
                                                {% if el.is_active %}
                                                    <i class="fas fa-check-circle"></i>
                                                {% else %}
                                                    <i class="fas fa-times-circle"></i>
                                                {% endif %}
                                            </td>

                                        </tr>
                                    {% endfor %}

                                </tbody>

                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admin_user_create' %}">
                            <button class="btn btn-success">Создать {{title}}</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-users-update-delete.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование пользователя | {{shopuser.username}}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admin_user_update' shopuser.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{form.first_name.id_for_label}}">Имя</label>
                                    {{form.first_name}}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{form.last_name.id_for_label}}">Фамилия</label>
                                    {{form.last_name}}
                                </div>
                            </div>
                        </div>
                        <div class="form-row mb-2">
                            <div class="col-lg-12">
                                <div class="custom-file">
                                    {{form.avatar}}
                                    <label class="custom-file-label" for="{{form.avatar.id_for_label}}">Выберите изображение</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-4">
                                <label class="small mb-1" for="{{form.username.id_for_label}}">Имя пользователя</label>
                                {{form.username}}
                            </div>
                            <div class="col-lg-4">
                                <label class="small mb-1" for="{{form.email.id_for_label}}">Адрес электронной
                                    почты</label>
                                {{form.email}}
                            </div>
                            <div class="col-lg-4">
                            <label class="small mb-1" for="{{form.age.id_for_label}}">Возраст</label>
                            {{form.age}}
                        </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                    </form>
                    <form action="{% url 'admins:admin_user_delete' shopuser.id %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                        </div>
                        </div>
                    </form>

                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin_category.html
{% extends 'admins/base.html' %}
{% block content %}
<div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">{{title}}</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        {{title}}
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Наименование</th>
                                        <th>Описание</th>
                                    </tr>
                                </thead>

                                <tbody>

                                {% for el in categoryes %}
                                    <tr>
                                    <td><a href="{% url 'admins:admin_categoryes_update' el.id %}" style="color: dodgerblue">{{el.id}}</a> </td>
                                    <td>{{el.name}}</td>
                                    <td>{{el.description}}</td>
                                    </tr>
                                {% endfor %}

                                </tbody>

                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admin_category_create' %}">
                            <button class="btn btn-success">Создать {{title}}</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin_category_create.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">{{title}}</h1>
                <form action="{% url 'admins:admin_category_create'%}" method="post" >
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label class="small mb-1" for="{{form.id.id_for_label}}">ID</label>
                                {{form.id}}
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label class="small mb-1" for="{{form.name.id_for_label}}">Наименование</label>
                                {{form.name}}
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label class="small mb-1" for="{{form.description.id_for_label}}">Описание</label>
                                {{form.description}}
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label class="small mb-1" for="{{form.discount.id_for_label}}">Скидка</label>
                                {{form.discount}}
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin_categoryes_update_delete.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">{{title}} | {{category.name}}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admin_categoryes_update' category.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-2">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{form.id.id_for_label}}">ID</label>
                                    {{form.id}}
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{form.name.id_for_label}}">Наименование</label>
                                    {{form.name}}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{form.description.id_for_label}}">Описание категории</label>
                                    {{form.description}}
                                </div>
                            </div>
                            <div class="col-lg-1">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{form.discount.id_for_label}}">Скидка</label>
                                    {{form.discount}}
                                </div>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                    </form>
                    <form action="{% url 'admins:admin_categoryes_delete' category.id %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="{% url 'admins:admin_categoryes_delete' category.id %}" type="submit" value="Удалить">
                        </div>
                        </div>
                    </form>

                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin_product.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">{{title}}</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        {{title}}
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">

                                <thead>

                                <tr>
                                    <th>ID</th>
                                    <th>Категория</th>
                                    <th>Имя продукта</th>
                                    <th>Фотография</th>
                                    <th>Краткое описание продукта</th>
                                    <th>Описание продукта</th>
                                    <th>Цена</th>
                                    <th>Количество</th>
                                </tr>
                                </thead>


                                <tbody>

                                    {% for el in products %}
                                        <tr>
                                            <td> <a href="{% url 'admins:admin_product_update' el.id %}" style="color: dodgerblue">{{el.id}}</a></td>
                                            <td>{{el.category}}</td>
                                            <td>{{el.name}}</td>
                                            <td>{{el.image}}</td>
                                            <td>{{el.short_desc}}</td>
                                            <td>{{el.description}}</td>
                                            <td>{{el.price}}</td>
                                            <td>{{el.quantity}}</td>

                                        </tr>
                                    {% endfor %}

                                </tbody>

                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admin_product_create' %}">
                            <button class="btn btn-success">Создать {{title}}</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin_product_create.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">{{title}}</h1>
                <form action="{% url 'admins:admin_product_create'%}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{form.category.id_for_label}}">Категория</label>
                                {{form.category}}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{form.name.id_for_label}}">Наименование продукта</label>
                                {{form.name}}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{form.image}}
                                <label class="custom-file-label" for="{{form.image.id_for_label}}">Выберите изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{form.short_desc.id_for_label}}">Краткое описание</label>
                            {{form.short_desc}}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{form.description.id_for_label}}">Описание товара</label>
                            {{form.description}}
                        </div>

                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{form.price.id_for_label}}">Цена</label>
                            {{form.price}}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{form.quantity.id_for_label}}">Количество товара</label>
                            {{form.quantity}}
                        </div>

                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin_product_update_delete.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование продукта | {{product.name}} {{product.id}}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admin_product_update' product.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{form.category.id_for_label}}">Категория</label>
                                    {{form.category}}
                                </div>
                            </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{form.name.id_for_label}}">Наименование продукта</label>
                                {{form.name}}
                            </div>
                        </div>
                        </div>
                        <div class="form-row mb-2">
                            <div class="col-lg-12">
                                <div class="custom-file">
                                    {{form.image}}
                                    <label class="custom-file-label" for="{{form.image.id_for_label}}">Выберите изображение</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{form.short_desc.id_for_label}}">Краткое описание</label>
                                {{form.short_desc}}
                            </div>
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{form.description.id_for_label}}">Описание товара</label>
                                {{form.description}}
                            </div>

                        </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{form.price.id_for_label}}">Цена</label>
                            {{form.price}}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{form.quantity.id_for_label}}">Количество товара</label>
                            {{form.quantity}}
                        </div>

                    </div>
                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                    </form>
                    <form action="{% url 'admins:admin_product_delete' product.id %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                        </div>
                        </div>
                    </form>

                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}